apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springbootapp-demo
  template:
    metadata:
      labels:
        app: springbootapp-demo
    spec:
      containers:
      - name: springbootapp-demo
        image: springdempapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
